### ISSUE TITLE
Code doesn't run on newer Ubuntu releases without python

### ISSUE THREAD

**Issue by CaptainEmerson** [sophieball/toxicity-detector#102]
As a consequence of https://github.com/bazelbuild/bazel/issues/11554, none of the build targets will run on my machine. That upstream bug doesn't look like it'll be fixed soon. I could install python-is-python2, but that's only a temporary fix. I can do python-is-python3, but does this code work python3?

**Comment by sophieball** [comment]
It is written in Python3, so I guess that should be ok.

**Comment by sophieball** [comment]
Did it work? I assume it might produce a different error message than the one you put in the PR?

**Comment by CaptainEmerson** [comment]
python-is-python3 seems to have worked.

For future reference, I tried setting python_version on the command line and in the BUILD file, to no avail.
