### ISSUE TITLE
Read text data from standard input

### ISSUE THREAD

**Issue by CaptainEmerson** [sophieball/toxicity-detector#15]
Here's some stub R code I'll be using to pass data into toxicity-detector:

```
df <- data.frame(
  id = c(1,2,3,4,5),
  text = c("great","not great", "you jerk", "bananas", "orange jerks"),
  toxic = c(F, F, T, F, NA),
  training = c(T, T, T, T, F)
)

system2("bazel-bin/src/train_classifier_g",
        stdout = T,
        input = write.csv(df))
```

[Example of how to read this from python](https://stackoverflow.com/questions/56234034/reading-csv-file-from-stdin-in-python-and-modifying-it).

**Comment by sophieball** [comment]
I've changed `toxic` to `lable, `write.csv` to `format.csv`
