### ISSUE TITLE
Politeness logistic regression R code missing `length` variable

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#50]
Closed #29 and moved the unsolved problem here.

**Comment by sophieball** [comment]
@CaptainEmerson If the code from the new PR works find, can you report the result in the log file, whose path will be printed to the R console, or where-ever you direct it to?
The goal is to see if the politeness strategies are different between pushback and non-pushback comments.

Putting this in the big picture: since we used perspective score and politeness score (aggregated over 20 different types) didn't give us 1's, maybe we should use fine-grained features like some specific politeness strategies.

**Comment by CaptainEmerson** [comment]
Appears fixed in #51
