### ISSUE TITLE
Convokit Prompt types: label prompt types

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#52]
Predicting Conversations Gone Awry With Convokit:
https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/convokit/forecaster/tests/cumulativeBoW_demo.ipynb

**Comment by sophieball** [comment]
Update: the one I put about doesn't work - it uses unigram and logistic regression - took too long and the program was killed
```
No model passed to Forecaster. Initializing default forecaster model: Cumulative Bag-of-words...
Initializing default unigram CountVectorizer...
Initializing default classification model (standard scaled logistic regression
```

Trying this: https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/tree/master/examples/conversations-gone-awry

This one also looks interesting: https://github.com/CornellNLP/Cornell-Conversational-Analysis-Toolkit/blob/master/examples/hyperconvo/demo_new.ipynb

**Comment by sophieball** [comment]
Update July 27: 
- I still have some questions on how exactly I should use the prompt type
- I'll be meeting with two of the authors from the pear-shaped conversations paper - so I can ask them what should I try
- Plan: finish trying some most related convokit transformers within these two weeks - then work on the write-up

**Comment by sophieball** [comment]
Update Aug 4:
Talked to one of the authors. Confirmed that we've been on the right track. Forgot to ask how to label prompts because we ran out of time.

**Comment by CaptainEmerson** [comment]
On your last day, we looked over this file. I have also set it aside on my desktop, should we need it later. I'll close this issue, but feel free to reopen if it's not done.
