### ISSUE TITLE
Cluster PB signals

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#59]
After talking to Lan, here's the plan:
1. Factor analysis on the 20 signals ([R tutorial and explanation](https://www.geo.fu-berlin.de/en/v/soga/Geodata-analysis/factor-analysis/A-simple-example-of-FA/index.html#:~:text=In%20the%20R%20software%20factor,specified%20by%20the%20argument%20factors%20.))
2. Depend on the output of step 1....

**Comment by sophieball** [comment]
https://www.geo.fu-berlin.de/en/v/soga/Geodata-analysis/factor-analysis/A-simple-example-of-FA/index.html#:~:text=In%20the%20R%20software%20factor,specified%20by%20the%20argument%20factors%20.

**Comment by sophieball** [comment]
How to determine the number of factors: https://www.theanalysisfactor.com/factor-analysis-how-many-factors/

**Comment by sophieball** [comment]
Rotation: https://www.theanalysisfactor.com/rotations-factor-analysis/

**Comment by sophieball** [comment]
clustering: https://www.datanovia.com/en/lessons/choosing-the-best-clustering-algorithms/#measures-for-comparing-clustering-algorithms

**Comment by sophieball** [comment]
@CaptainEmerson 
#61 contains the R code for factor analysis. When you run it, please only feed in relevant columns (the 20 signals). It will produce several plots (`scree.png`, etc) and an output file `factor.out`. Can you run the code and send me the output?

**Comment by CaptainEmerson** [comment]
I will run the program three times:
* Once with the first 4 likert signals
* Once with the first 5 likert signals
* Once for the 20+ boolean signals

**Comment by sophieball** [comment]
I think we probably don't need to run the first 4 or 5 columns with factor analysis - it's column based clustering, reducing the number of columns based on the values in each column. 4 or 5 columns are already very minimum. They can only be reduced down to 2 factors.

**Comment by sophieball** [comment]
Update July 27: A singular matrix problem reported in PR #61. I've left a message for Lan.

**Comment by CaptainEmerson** [comment]
Works! I put the results in our shared folder.

**Comment by sophieball** [comment]
Oh it looks very interesting!
