### ISSUE TITLE
Data for clustering

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#60]
@CaptainEmerson Is [this](https://drive.google.com/file/d/1IjgqAKpRkFquWT-CSdjB2VmcOjF7EWfx/view?usp=sharing) an ok approximation to the data? Ignore value distributions and assume there are 20 columns with `label_`

**Comment by CaptainEmerson** [comment]
Good idea to mock out this data. 

Some notes on the schema:
* The "label" should probably not be in there. So far this value has been calculated as a heuristic combination of the other values
* rounds	review_time	shepherding_time	conflict	too_long	changes	future_CR	frustration should be all prefixed with label_*, right?

Regarding the values:
* For realism, conflict	too_long	changes	future_CR	frustration should probably have a few NAs mixed in
* For realism, conflict	too_long	changes	future_CR	frustration should be all nulls in some rows, but with complete values in label_* columns
* ... and vice-versa: in some rows, label_* should be all nulls, with complete values in conflict	too_long	changes	future_CR	frustration
* What's currently label_* are going to be all booleans

**Comment by sophieball** [comment]
Oh! I forgot to put NAs!!
Are there any rows without any nulls?

**Comment by CaptainEmerson** [comment]
There are no complete rows.
