### ISSUE TITLE
Examine Fighting Words from G Data Set

### ISSUE THREAD

**Issue by CaptainEmerson** [sophieball/toxicity-detector#66]
Some interesting fighting words popped up. What do they mean in context? How are people using them?

**Comment by CaptainEmerson** [comment]
Ciera says: Are go/ links more likely to appear in readability reviews?

**Comment by sophieball** [comment]
Ciera also suggested removing "please fix"

**Comment by sophieball** [comment]
I pushed the updated code in #41 that will include unigram in the analysis and save everything into csvs instead of plots. The code handles both fighting words and politeness strategies' word-counts

**Comment by CaptainEmerson** [comment]
Groovy. Re, "please fix", I think that it's still meaningful, but I'll change it to a single token.

**Comment by CaptainEmerson** [comment]
I've removed some machine-generated comments, but there's still a few for me to do.
