### ISSUE TITLE
Annotated factor analysis output

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#67]
@CaptainEmerson 

Based on [this webpage](https://www.geo.fu-berlin.de/en/v/soga/Geodata-analysis/factor-analysis/A-simple-example-of-FA/index.html), I annotated the factor analysis output, which is a Gdoc in the same folder you put the raw output. I also added a comment on `scree_20-07-30_21:43:15.png`.

You can read them at your leisure =p

**Comment by CaptainEmerson** [comment]
Thanks! I've added another folder for clusters 3:9. No need to re-annotate. Let me know if you need more for this milestone.
