### ISSUE TITLE
Sample 10K CLs from this year and train prompt types

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#72]
#71 contains the code to train an unsupervised classifier using 10K code reviews

**Comment by CaptainEmerson** [comment]
@sophieball Just to clarify, I should run on the train_prompt_types target, with a CSV schema that's the same as data/pr_body_comments.csv?

**Comment by CaptainEmerson** [comment]
Each row is a one comment.
- _id -- pr id
- id -- id of that comment (must by unique within PR). need not be sorted
- timestamp -- for sorting

We don't have:

- reply to. "NONE"
- author association. "NONE"

**Comment by CaptainEmerson** [comment]
@sophieball I ran this and uploaded the results to Drive, but I'm not sure what I'm looking at. I can also show you a sample of the data I fed in.

**Comment by sophieball** [comment]
8/14 doesn't seem like the output from prompt types. They look like old output from fighting words and politeness

**Comment by CaptainEmerson** [comment]
Success!
