### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by sophieball** [sophieball/toxicity-detector#87]
@CaptainEmerson Do you remember the list of sentiment analysis tools we should use? You mentioned [sentimoji](https://github.com/SEntiMoji/SEntiMoji)

**Comment by CaptainEmerson** [comment]
[Sentimoji](https://arxiv.org/pdf/1907.02202.pdf) is recent enough that the paper describes the performance of all the recent ones I'm aware of. This [paper](http://www.bowenxu.me/publications/ICSME2020.pdf) is on the topic and is recent as of 2020, so it might have a more up-to-date review.

Random: [this looks](https://andrewbegel.com/papers/affect-recognition-in-situ-biometric-study.pdf) interesting.

**Comment by sophieball** [comment]
Senti4SD has a problem: it needs the data as a csv file. I'm been trying to modify the code but I can't modify their `.jar` file. But I found [a library that can use Senti4SD on R dataframes](https://github.com/M3SOulu/RSenti4SD) .

**Comment by sophieball** [comment]
@CaptainEmerson `Senti4SD` needs the data on disk as a csv. Is it ok if the program `RSentiSD` writes it to a tmp file and removes it when done? I don't see any alternatives. I asked the developers and they don't seem to have a workaround either.

**Comment by CaptainEmerson** [comment]
Putting the comments on disk seems fine, though not ideal. Please put it in /tmp and ensure that it gets deleted, even if the program does not complete successfully.

I'm a little more concerned that Senti4SD [seems to use a bunch of binaries](https://github.com/collab-uniba/Senti4SD), rather than being built from source. So it's hard to tell what the code is doing (e.g., is it sending my data to some cloud?). Or can you build it from source?

**Comment by sophieball** [comment]
No, I can't get the source code. I emailed the maintainers and they told me it's "a legacy part that we're getting rid of." I just emailed the developer again to ask if they've made progress.

**Comment by CaptainEmerson** [comment]
Huh. The worry here is that we're executing some untrusted binary that could be executing anything. Browsing a few of their dependencies, they're at least using apache http for some reason.

How badly do we want to put sensitive data into this binary? Arguably it's fine to do it on public github data in a sandbox, but I'm reticent to do it with my data.

**Comment by sophieball** [comment]
The answer I got from the developers: We are working at an API that should be accessible by the end of summer. Would that work for you?

**Comment by bvasiles** [comment]
Is there any other sentiment analyzer that might work? Even if less SE specific

**Comment by sophieball** [comment]
How about this one: https://github.com/senticr/SentiCR

**Comment by bvasiles** [comment]
Sure, or a general purpose one trained on tons of data, I don’t know what’s popular these days.

**Comment by CaptainEmerson** [comment]
Senti-CR seems simple enough and has some pretty standard dependencies, so I'd be comfortable running our data through it. If we go with it, it'd be convenient for me if it were built with bazel; that might be a nice contribution back to the project, too.
